In [8]:
import pandas as pd
from pandas import DataFrame
import numpy as np

primitive_data=pd.read_csv("C:\\Users\\win11\\Downloads\\data.csv", encoding="gbk")
primitive_data

,from_dev,from_port,from_city,from_level,to_dev,to_port,to_city,to_level,traffic,bandwidth
0,47,71,通辽,一般节点,1756,585,北京,网络核心,49636052613,1.000000e+11
1,47,74,通辽,一般节点,1756,776,北京,网络核心,50056871412,1.000000e+11
2,47,240,通辽,一般节点,1756,802,北京,网络核心,49453581081,1.000000e+11
3,47,241,通辽,一般节点,1997,464,天津,网络核心,49733361585,1.000000e+11
4,47,242,通辽,一般节点,474,672,哈尔滨,一般节点,50492573662,1.000000e+11
...,...,...,...,...,...,...,...,...,...,...
1113,1129,546,上海,网络核心,2050,502,石家庄,网络核心,48731433404,1.000000e+11
1114,1129,514,上海,网络核心,2473,946,吉林,一般节点,50060666120,1.000000e+11
1115,36036,499,长春,一般节点,1257,178,上海,网络核心,50545082113,1.000000e+11
1116,36422,346,天津,网络核心,1997,41,天津,网络核心,50628787089,1.000000e+11
1117,2701,619,大连,网络核心,2549,1070,沈阳,网络核心,48753971761,1.000000e+11

In [9]:
primitive_data_1=primitive_data.dropna(how='any')
primitive_data_1

,from_dev,from_port,from_city,from_level,to_dev,to_port,to_city,to_level,traffic,bandwidth
0,47,71,通辽,一般节点,1756,585,北京,网络核心,49636052613,1.000000e+11
1,47,74,通辽,一般节点,1756,776,北京,网络核心,50056871412,1.000000e+11
2,47,240,通辽,一般节点,1756,802,北京,网络核心,49453581081,1.000000e+11
3,47,241,通辽,一般节点,1997,464,天津,网络核心,49733361585,1.000000e+11
4,47,242,通辽,一般节点,474,672,哈尔滨,一般节点,50492573662,1.000000e+11
...,...,...,...,...,...,...,...,...,...,...
1113,1129,546,上海,网络核心,2050,502,石家庄,网络核心,48731433404,1.000000e+11
1114,1129,514,上海,网络核心,2473,946,吉林,一般节点,50060666120,1.000000e+11
1115,36036,499,长春,一般节点,1257,178,上海,网络核心,50545082113,1.000000e+11
1116,36422,346,天津,网络核心,1997,41,天津,网络核心,50628787089,1.000000e+11
1117,2701,619,大连,网络核心,2549,1070,沈阳,网络核心,48753971761,1.000000e+11

In [10]:
data_before_filter=primitive_data_1
data_after_filter_1=data_before_filter.loc[data_before_filter["traffic"]!=0]
data_after_filter_2=data_after_filter_1.loc[data_after_filter_1["from_level"]=='一般节点']
data_after_filter_2

,from_dev,from_port,from_city,from_level,to_dev,to_port,to_city,to_level,traffic,bandwidth
0,47,71,通辽,一般节点,1756,585,北京,网络核心,49636052613,1.000000e+11
1,47,74,通辽,一般节点,1756,776,北京,网络核心,50056871412,1.000000e+11
2,47,240,通辽,一般节点,1756,802,北京,网络核心,49453581081,1.000000e+11
3,47,241,通辽,一般节点,1997,464,天津,网络核心,49733361585,1.000000e+11
4,47,242,通辽,一般节点,474,672,哈尔滨,一般节点,50492573662,1.000000e+11
...,...,...,...,...,...,...,...,...,...,...
1097,2473,1460,吉林,一般节点,591,586,绥化,一般节点,48409925693,1.000000e+11
1103,36036,18,长春,一般节点,3443,650,青岛,网络核心,48663350759,1.000000e+11
1104,63,6,通辽,一般节点,36036,20,长春,一般节点,50355678076,1.000000e+11
1107,36036,52,长春,一般节点,1129,171,上海,网络核心,49345226162,1.000000e+11
1115,36036,499,长春,一般节点,1257,178,上海,网络核心,50545082113,1.000000e+11

In [12]:
data_before_sample=data_after_filter_2
columns=data_before_sample.columns
weight_sample=data_before_sample.copy()
weight_sample['weight']=0
for i in weight_sample.index:
    if weight_sample.at[i,'to_level']=='一般节点':
        weight=1
    else:
        weight=5
        weight_sample.at[i,'weight']=weight

weight_sample_finish=weight_sample.sample(n=50,weights='weight')
#data_before_sample=data_before_sample[columns]
weight_sample_finish=weight_sample[columns]
weight_sample_finish

,from_dev,from_port,from_city,from_level,to_dev,to_port,to_city,to_level,traffic,bandwidth
0,47,71,通辽,一般节点,1756,585,北京,网络核心,49636052613,1.000000e+11
1,47,74,通辽,一般节点,1756,776,北京,网络核心,50056871412,1.000000e+11
2,47,240,通辽,一般节点,1756,802,北京,网络核心,49453581081,1.000000e+11
3,47,241,通辽,一般节点,1997,464,天津,网络核心,49733361585,1.000000e+11
4,47,242,通辽,一般节点,474,672,哈尔滨,一般节点,50492573662,1.000000e+11
...,...,...,...,...,...,...,...,...,...,...
1097,2473,1460,吉林,一般节点,591,586,绥化,一般节点,48409925693,1.000000e+11
1103,36036,18,长春,一般节点,3443,650,青岛,网络核心,48663350759,1.000000e+11
1104,63,6,通辽,一般节点,36036,20,长春,一般节点,50355678076,1.000000e+11
1107,36036,52,长春,一般节点,1129,171,上海,网络核心,49345226162,1.000000e+11
1115,36036,499,长春,一般节点,1257,178,上海,网络核心,50545082113,1.000000e+11

In [13]:
random_sample=data_before_sample
random_sample_finish=random_sample.sample(n=50)
random_sample_finish=random_sample_finish[columns]
random_sample_finish

,from_dev,from_port,from_city,from_level,to_dev,to_port,to_city,to_level,traffic,bandwidth
94,180,485,呼和浩特,一般节点,36422,102,天津,网络核心,52460156321,1.000000e+11
52,96,157,呼和浩特,一般节点,2050,443,石家庄,网络核心,50096366926,1.000000e+11
537,47,314,通辽,一般节点,1756,1008,北京,网络核心,49136293957,1.000000e+11
1103,36036,18,长春,一般节点,3443,650,青岛,网络核心,48663350759,1.000000e+11
84,180,214,呼和浩特,一般节点,2701,135,大连,网络核心,48901190886,1.000000e+11
325,96,155,呼和浩特,一般节点,5242,537,西安,网络核心,48893583868,1.000000e+11
406,474,1473,哈尔滨,一般节点,36422,394,天津,网络核心,48378712039,1.000000e+11
117,474,1228,哈尔滨,一般节点,1997,468,天津,网络核心,49556923953,1.000000e+11
436,591,1266,绥化,一般节点,2050,505,石家庄,网络核心,51285397493,1.000000e+11
889,63,12,通辽,一般节点,1997,86,天津,网络核心,49823274555,1.000000e+11
19,63,12,通辽,一般节点,180,252,呼和浩特,一般节点,49290094443,1.000000e+11
83,180,210,呼和浩特,一般节点,2194,450,唐山,网络核心,50514699101,1.000000e+11
902,96,141,呼和浩特,一般节点,2050,335,石家庄,网络核心,51273380868,1.000000e+11
330,96,336,呼和浩特,一般节点,1756,1106,北京,网络核心,51277669375,1.000000e+11
540,47,427,通辽,一般节点,2549,1430,沈阳,网络核心,50264080533,1.000000e+11
167,787,51,玉溪,一般节点,4561,1033,成都,网络核心,51033155364,1.000000e+11
376,474,460,哈尔滨,一般节点,3757,122,福州,一般节点,48394911971,1.000000e+11
75,180,84,呼和浩特,一般节点,1536,86,鄂尔多斯,网络核心,49100967003,1.000000e+11
415,591,56,绥化,一般节点,36422,230,天津,网络核心,47741796615,1.000000e+11
414,591,29,绥化,一般节点,235,1649,北京,网络核心,49268934149,1.000000e+11
433,591,1112,绥化,一般节点,2360,236,太原,网络核心,50670449325,1.000000e+11
566,591,586,绥化,一般节点,1129,514,上海,网络核心,49995510331,1.000000e+11
1104,63,6,通辽,一般节点,36036,20,长春,一般节点,50355678076,1.000000e+11
541,63,6,通辽,一般节点,2473,1043,吉林,一般节点,48954016072,1.000000e+11
351,180,90,呼和浩特,一般节点,1257,132,上海,网络核心,49446475351,1.000000e+11
355,180,200,呼和浩特,一般节点,1536,2309,广州,网络核心,49873632464,1.000000e+11
93,180,276,呼和浩特,一般节点,36272,235,太原,网络核心,51775514286,1.000000e+11
292,63,6,通辽,一般节点,2841,418,郑州,网络核心,51392218854,1.000000e+11
1057,47,243,通辽,一般节点,2473,769,吉林,一般节点,49117847542,1.000000e+11
128,474,1409,哈尔滨,一般节点,1756,1067,北京,网络核心,49473981680,1.000000e+11
172,787,63,玉溪,一般节点,1536,1882,广州,网络核心,50068630781,1.000000e+11
377,474,467,哈尔滨,一般节点,5058,70,南宁,一般节点,51745421052,1.000000e+11
27,63,224,通辽,一般节点,180,20,呼和浩特,一般节点,48761650539,1.000000e+11
399,474,1311,哈尔滨,一般节点,1997,213,天津,网络核心,50081963602,1.000000e+11
799,180,52,呼和浩特,一般节点,474,460,哈尔滨,一般节点,49553070694,1.000000e+11
136,591,19,绥化,一般节点,36036,18,长春,一般节点,49524524277,1.000000e+11
428,591,1028,绥化,一般节点,36422,230,天津,网络核心,50678848280,1.000000e+11
728,2473,946,吉林,一般节点,2701,195,大连,网络核心,52184126133,1.000000e+11
305,63,232,通辽,一般节点,2549,1066,沈阳,网络核心,49269663214,1.000000e+11
980,4360,472,南京,一般节点,63,286,通辽,一般节点,49837582425,1.000000e+11
276,47,74,通辽,一般节点,4561,1033,成都,网络核心,50819524115,1.000000e+11
549,63,70,通辽,一般节点,2473,1460,吉林,一般节点,49551919218,1.000000e+11
303,63,228,通辽,一般节点,1536,398,广州,网络核心,50443480874,1.000000e+11
339,180,18,呼和浩特,一般节点,47,241,通辽,一般节点,51793025548,1.000000e+11
110,474,672,哈尔滨,一般节点,47,242,通辽,一般节点,51555817613,1.000000e+11
284,47,252,通辽,一般节点,5058,118,南宁,一般节点,49295040137,1.000000e+11
180,787,360,玉溪,一般节点,3615,191,长沙,一般节点,49629725686,1.000000e+11
773,2473,762,吉林,一般节点,180,84,呼和浩特,一般节点,49702910101,1.000000e+11
498,47,314,通辽,一般节点,591,586,绥化,一般节点,50043006782,1.000000e+11
22,63,60,通辽,一般节点,36422,258,天津,网络核心,49920786706,1.000000e+11

In [14]:
ybjd=data_before_sample.loc[data_before_sample['to_level']=='一般节点']
wlhx=data_before_sample.loc[data_before_sample['to_level']=='网络核心']
after_sample=pd.concat([ybjd.sample(17),wlhx.sample(33)])
after_sample

,from_dev,from_port,from_city,from_level,to_dev,to_port,to_city,to_level,traffic,bandwidth
824,47,252,通辽,一般节点,474,1389,哈尔滨,一般节点,51228405663,1.000000e+11
874,36539,1140,杭州,一般节点,787,324,玉溪,一般节点,48801407907,1.000000e+11
299,63,66,通辽,一般节点,47,249,通辽,一般节点,48811485662,1.000000e+11
743,4069,1195,宁波,一般节点,96,134,呼和浩特,一般节点,50099141709,1.000000e+11
791,180,264,呼和浩特,一般节点,180,276,呼和浩特,一般节点,49965760241,1.000000e+11
775,96,134,呼和浩特,一般节点,180,98,呼和浩特,一般节点,51993612239,1.000000e+11
1035,36036,54,长春,一般节点,591,23,绥化,一般节点,50638071722,1.000000e+11
396,474,1269,哈尔滨,一般节点,96,152,呼和浩特,一般节点,50191686376,1.000000e+11
416,591,60,绥化,一般节点,180,52,呼和浩特,一般节点,50126205393,1.000000e+11
25,63,70,通辽,一般节点,180,264,呼和浩特,一般节点,49630519508,1.000000e+11
59,96,391,呼和浩特,一般节点,47,417,通辽,一般节点,51570663870,1.000000e+11
91,180,264,呼和浩特,一般节点,63,70,通辽,一般节点,50106121660,1.000000e+11
160,591,1258,绥化,一般节点,4448,127,无锡,一般节点,50322958171,1.000000e+11
559,96,102,呼和浩特,一般节点,36036,52,长春,一般节点,49483965391,1.000000e+11
555,63,278,通辽,一般节点,36036,18,长春,一般节点,50478302302,1.000000e+11
1031,591,23,绥化,一般节点,96,152,呼和浩特,一般节点,51357214855,1.000000e+11
542,63,10,通辽,一般节点,4360,472,南京,一般节点,49716409605,1.000000e+11
68,180,30,呼和浩特,一般节点,235,1661,北京,网络核心,49596659754,1.000000e+11
419,591,98,绥化,一般节点,3227,781,济南,网络核心,50666845945,1.000000e+11
701,2473,803,吉林,一般节点,2194,406,唐山,网络核心,48906180396,1.000000e+11
566,591,586,绥化,一般节点,1129,514,上海,网络核心,49995510331,1.000000e+11
738,2473,803,吉林,一般节点,235,1621,北京,网络核心,49820870504,1.000000e+11
620,180,264,呼和浩特,一般节点,1129,546,上海,网络核心,50207994896,1.000000e+11
448,787,307,玉溪,一般节点,36422,258,天津,网络核心,51727332383,1.000000e+11
174,787,316,玉溪,一般节点,1257,177,上海,网络核心,51407063255,1.000000e+11
430,591,1082,绥化,一般节点,1257,560,上海,网络核心,49355162407,1.000000e+11
393,474,1238,哈尔滨,一般节点,1997,122,天津,网络核心,49693039378,1.000000e+11
681,36036,20,长春,一般节点,1536,681,广州,网络核心,49317137743,1.000000e+11
1,47,74,通辽,一般节点,1756,776,北京,网络核心,50056871412,1.000000e+11
415,591,56,绥化,一般节点,36422,230,天津,网络核心,47741796615,1.000000e+11
283,47,251,通辽,一般节点,1257,177,上海,网络核心,49380930804,1.000000e+11
150,591,582,绥化,一般节点,2701,619,大连,网络核心,50838395442,1.000000e+11
363,180,254,呼和浩特,一般节点,2360,62,太原,网络核心,50252917820,1.000000e+11
538,47,417,通辽,一般节点,3227,705,济南,网络核心,49998156282,1.000000e+11
413,591,27,绥化,一般节点,36422,124,天津,网络核心,49718002453,1.000000e+11
168,787,52,玉溪,一般节点,3213,246,重庆,网络核心,50468642387,1.000000e+11
487,47,240,通辽,一般节点,235,1661,北京,网络核心,49873119534,1.000000e+11
608,96,152,呼和浩特,一般节点,1385,1490,广州,网络核心,50846379751,1.000000e+11
131,474,1473,哈尔滨,一般节点,2549,1461,沈阳,网络核心,53304989080,1.000000e+11
95,474,359,哈尔滨,一般节点,2050,502,石家庄,网络核心,51299508559,1.000000e+11
600,96,124,呼和浩特,一般节点,1756,1127,北京,网络核心,48884918110,1.000000e+11
341,180,26,呼和浩特,一般节点,1756,796,北京,网络核心,48797633450,1.000000e+11
344,180,34,呼和浩特,一般节点,2050,295,石家庄,网络核心,50352242512,1.000000e+11
336,96,407,呼和浩特,一般节点,3227,188,济南,网络核心,50219393940,1.000000e+11
167,787,51,玉溪,一般节点,4561,1033,成都,网络核心,51033155364,1.000000e+11
420,591,100,绥化,一般节点,235,112,北京,网络核心,51157112955,1.000000e+11
438,591,1284,绥化,一般节点,2841,237,郑州,网络核心,49402368215,1.000000e+11
107,474,614,哈尔滨,一般节点,3227,724,济南,网络核心,51504522549,1.000000e+11
105,474,474,哈尔滨,一般节点,2360,213,太原,网络核心,49764093255,1.000000e+11
6,47,249,通辽,一般节点,1997,85,天津,网络核心,50499586948,1.000000e+11